name: shop_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  connectivity_plus: ^4.0.1
  retrofit: ^4.0.3
  freezed_annotation: ^2.4.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  analyzer: ^6.1.0
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  get_it: ^7.6.0
  rxdart: ^0.27.7
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/product-placeholder.png
  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 900
        - asset: assets/fonts/Lato-Regular.ttf
